jobs:
  build1:
    docker:
      - image: cyversevice/jupyterlab-scipy:latest
    steps:
      - checkout
      - run: jupyter lab --version
  build2:
    docker:
      - image: cyversevice/jupyterlab-scipy:gee-latest
    steps:
      - checkout
      - run: jupyter lab --version
  build3:
    docker:
      - image: cyversevice/jupyterlab-scipy:earthlab-latest
    steps:
      - checkout
      - run: jupyter lab --version    
 build4:
    docker:
      - image: cyversevice/jupyterlab-scipy:0.35.0
    steps:
      - checkout
      - run: jupyter lab --version    
build5:
    docker:
      - image: cyversevice/jupyterlab-scipy:1.0.9
    steps:
      - checkout
      - run: jupyter lab --version    
build6:
    docker:
      - image: cyversevice/jupyterlab-scipy:1.1.0
    steps:
      - checkout
      - run: jupyter lab --version    
build7:
    docker:
      - image: cyversevice/jupyterlab-scipy:1.2.0
    steps:
      - checkout
      - run: jupyter lab --version    
build8:
    docker:
      - image: cyversevice/jupyterlab-scipy:2.0.1
    steps:
      - checkout
      - run: jupyter lab --version    
build9:
    docker:
      - image: cyversevice/jupyterlab-scipy:2.0.2
    steps:
      - checkout
      - run: jupyter lab --version    
build10:
    docker:
      - image: cyversevice/jupyterlab-scipy:2.1.0
    steps:
      - checkout
      - run: jupyter lab --version    
workflows:
  version: 2
  build1_to_build10:
    jobs:
      - build1
      - build2
      - build3
      - build4
      - build5
      - build6
      - build7
      - build8
      - build9
      - build10
      
