jobs:
  build1:
    docker:
      - image: cyversevice/jupyterlab-scipy:latest
    steps:
      - checkout
      - run: jupyter lab --version
  build2:
    docker:
      - image: cyversevice/jupyterlab-scipy:2.2.9
    steps:
      - checkout
      - run: jupyter lab --version    
  build3:
    docker:
      - image: cyversevice/jupyterlab-scipy:1.0.9
    steps:
      - checkout
      - run: jupyter lab --version      
workflows:
  version: 2
  build1_to_build8:
    jobs:
      - build1
      - build2
      - build3
